name: build&test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: get flex/bison
      run: sudo apt-get install flex bison
    - name: Compile GTest
      run: |
        cmake libs/CLI11/extern/googletest/googletest/CMakeLists.txt
        make -C libs/CLI11/extern/googletest/googletest/
    - name: make epa
      run: make -j
    - name: run tests
      run: ./test/bin/epa_test
